### ISSUE TITLE
Build linux wheels for package on pypi

### ISSUE THREAD

**Issue by salekseev** [lithammer/python-jump-consistent-hash#14]
Perhaps something like this https://github.com/joerick/cibuildwheel could be used to achieve this?

**Comment by lithammer** [comment]
I've manually built and uploaded wheels for Linux and macOS using https://github.com/pypa/manylinux and https://github.com/pypa/python-manylinux-demo.

It's a shame there isn't a lot to do about musl-based distros like alpine though...

https://pypi.org/project/jump-consistent-hash/3.0.2/#files
